# Generated by Django 5.1.2 on 2024-10-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='LoginModel',
        ),
    ]
