# Generated by Django 5.1.2 on 2024-11-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_login_loginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='posts')),
                ('description', models.CharField(blank=True, max_length=50)),
                ('tag', models.ManyToManyField(to='store.tagmodel')),
            ],
        ),
    ]
