# Generated by Django 5.1.2 on 2024-11-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_tagmodel_alter_loginmodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
