# Generated by Django 5.1.2 on 2024-11-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_articlemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
