# Generated by Django 5.1.2 on 2024-11-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_articlemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
