# Generated by Django 5.1.2 on 2024-11-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_articlemodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='slug',
        ),
    ]
