# Generated by Django 5.1.2 on 2024-11-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_articlemodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
